[frame]
processor = "vulkan"
# capturer = "wlroots" # both capture screen contents and use ALS
capturer = "none" # just use ALS to predict screen brightness

[als.iio]
path = "/sys/bus/iio/devices"
thresholds = { 0 = "dark", 10 = "dim", 80 = "normal", 250 = "bright", 500 = "outdoors" }

[[output.backlight]]
name = "eDP-1"
path = "/sys/class/backlight/intel_backlight"
capturer = "none"

# [[output.ddcutil]]
# name = "Acer Technologies SA220Q"
