[frame]
processor = "vulkan"
capturer = "wlroots"
# capturer = "none" # Does not capture screen contents, just uses ALS to predict ideal screen brightness

[als.iio]
path = "/sys/bus/iio/devices"
thresholds = [ 20, 80, 250, 500, 800 ]

# [als.time]
# hour_to_lux = { 7 = 1, 9 = 2, 11 = 3, 13 = 4, 16 = 3, 18 = 1, 20 = 0 }

# [als.none]

# multi-monitor setup is not supported yet
[output.backlight.eDP-1]
path = "/sys/class/backlight/intel_backlight"
