name: "Build Nix environments"

on:
  pull_request:
  push:
    branches:
      - master
    paths:
      - "**"
      - "README.org"

jobs:
  build-mbp16:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.4pre20210823_af94b54/install
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v10
      with:
        name: yevhenshymotiuk
        authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
    - name: Disable some darwin packages
      run: |
        sed -i "" \
          -e "/\s*Spotify\s*$/d" \
          ./platforms/darwin/home/packages.nix
    - name: Build flake
      run: nix build .#darwinConfigurations.mbp16.system
