name: "Check flake"

on:
  pull_request:
  push:
    branches:
      - master
    paths:
      - "**"
      - "README.org"

jobs:
  check-flake:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.4pre20210823_af94b54/install
        extra_nix_config: experimental-features = nix-command flakes
    - name: Check flake
      run: nix flake check
