name: "Test"
on:
  pull_request:
  push:
jobs:
  test-mbp16:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: darwin-config=/Users/runner/work/nix-config/nix-config/configuration.nix:/Users/runner/.nix-defexpr/channels:nixpkgs=channel:nixpkgs-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: yevhenshymotiuk
        authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
    - run: nix-channel --add https://github.com/yevhenshymotiuk/nixpkgs/archive/nixpkgs-unstable.tar.gz nixpkgs
    - run: nix-channel --add https://github.com/LnL7/nix-darwin/archive/master.tar.gz darwin
    - run: nix-channel --add https://github.com/rycee/home-manager/archive/master.tar.gz home-manager
    - run: nix-channel --update
    - run: ln -s ./machines/mbp16 host.nix
    - run: sed -i "" -- "s/darwinConfig = \"\$HOME\/.nixpkgs\/configuration.nix\"/darwinConfig = \"\$HOME\/work\/nix-config\/nix-config\/configuration.nix\"/g" ./platforms/darwin/default.nix
      # disable packages: cachix would be a duplicate, Spotify has a hash mismatch issue
    - run: sed -i "" -e "/\s*cachix\s*$/d" -e "/\s*Spotify\s*$/d" ./platforms/darwin/home/packages.nix
    - run: find . -type f -path "*.nix" -exec sed -i "" -- "s/yevhenshymotiuk/runner/g" {} +
    - run: ./platforms/darwin/nix-darwin-install.sh
