name: "Test"
on:
  pull_request:
  push:
jobs:
  test-mbp16:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: yevhenshymotiuk
        authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
    - run: nix-channel --add https://github.com/yevhenshymotiuk/nixpkgs/archive/nixpkgs-unstable.tar.gz nixpkgs
    - run: nix-channel --add https://github.com/LnL7/nix-darwin/archive/master.tar.gz darwin
    - run: nix-channel --add https://github.com/rycee/home-manager/archive/master.tar.gz home-manager
    - run: nix-channel --update
    - run: ln -snf ./machines/mbp16 host.nix
    - run: export NIX_PATH="darwin-config=$HOME/.nixpkgs/configuration.nix:/nix/var/nix/profiles/per-user/root/channels:$HOME/.nix-defexpr/channels"
    - run: ./platforms/darwin/nix-darwin-install.sh
    - run: NIX_PATH="darwin-config=$HOME/.nixpkgs/configuration.nix:/nix/var/nix/profiles/per-user/root/channels:$HOME/.nix-defexpr/channels"
 $(nix-build '<darwin>' -A system)/sw/bin/darwin-rebuild switch
